[package]
name = "pt-sound"
version = "0.1.0"
authors = ["jrkolsby <jrkolsby@mac.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sample = "0.7"
alsa = "0.2"
clap = "2.20"
wavefile = "0.2.0"
