# Colors
#    "bright-black"
[colors]
    background = "black"
    shadow     = ["222222"]
    view       = "#d3d7cf"

    primary   = ["#111111"]
    secondary = "#EEEEEE"
    tertiary  = "#444444"

    title_primary   = "#ff5555"
    title_secondary = "#ffff55"

    highlight          = "#F00"
    highlight_inactive = "#5555FF"
