[package]
name = "pt-input"
version = "0.1.0"
authors = ["James Kolsby <jrkolsby@mac.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.62"
linux_raw_input_rs = "0.1.6"
