[colors]
    background = "black"
    shadow     = "black" 
    view       = "black"
    
    primary   = "white"
    secondary = "white"
    tertiary  = "white"
   
    title_primary = "white" 
    title_secondary = "blue"

    highlight          = "#f94a32"
    highlight_inactive = "#295e99"
